### PR TITLE
187 write answers and explanations

### LINKED ISSUE #183: Minor Update: Fix spacing/complete paragraph in Lesson 4 Page
image
Add some spacing between the last line and just remove the For example,
Should look like this instead (from Figma):
image

### LINKED ISSUE #187: Feature: Write Answers/Explanations for Excercise 1 Page
We have the components in, so now we need to add in answers into the dropdowns along with explanations of why answer choices are right or wrong. Try to also link the correct/incorrect options to the check button.
These are the answers/explanations I thought of, feel free to suggest any edits:
Q1. 
10 - Not Quite. box b does not cover this address at all. Please try again.
11- Correct! This is the first address for box b, which is what pointers use to find variables in memory. Now Pipi needs to calculate how much he needs to move to get there.
12- Not Quite. This is the second address for box b, pointers don't want to point to the middle of a variable in memory, or it will read the incorrect value. It is like pointing to the middle of a word and starting to read from there! Please try again.
13- Not Quite. This is the end of box b. Remember that memory is read from left to right, just like our warehouse has addresses from left to right. Please try again.
Q2. 
7- Not Quite. Pipi needs to move from address 3 to address 11. Please try again.
8- Correct! Pipi needs to move from address 3 to address 11. Now Pipi needs to go to a different box.
9- Not Quite. Pipi needs to move from address 3 to address 11. Please try again.
Q3. 
21 - Not Quite. box e does not cover this address at all. Please try again.
22- Correct! This is the first address for box e, which is what pointers use to find variables in memory. Now Pipi needs to calculate how much he needs to move to get there.
23- Not Quite. This is the second address for box e, pointers don't want to point to the middle of a variable in memory, or it will read the incorrect value. It is like pointing to the middle of a word! Please try again.
24- Not Quite. This is the end of box e. Remember that memory is read from left to right, just like our warehouse has addresses from left to right. Please try again.
Q4.
10- Not Quite. Pipi needs to move from address 11 to address 22. Please try again.
11- Correct! Pipi needs to move from address 11 to address 22. Thanks to you, Pipi found all of the boxes correctly!
12- Not Quite. Pipi needs to move from address 11 to address 22. Please try again.

### PR DESCRIPTION
**Pull request by Dankco**
## Summary

Closes #187

- Made new state in parent called `correctAnswer` that is a boolean array saying which dropdowns are currently correct.
- Passed down `correctAnswer` and index to index the array in the dropdown and question components
- Put in explanations for correct and incorrect choices. Note that the incorrect choices are all the same right now, instead of analyzing why the specific dropdown was wrong. This would probably require some more work with lifting the state of ids from the dropdown to the page.

## Screenshots
image

### CODE REVIEW

File: src/pages/Exercise1.tsx [hunk 1]
```diff
@@ -38,13 +46,18 @@ const Exercise1: FC = () => {
...
+                    setCorrectAnswer={setCorrectAnswer}
+                    index={0}
                   />
                 </span>
               </p>
             </Question>
             <Question
-              correct="Correct! Now Pipi needs to..."
-              incorrect="Not quite. Think about ... Please try again."
+              correct="Correct! Pipi needs to move from address 3 to address 11. Now Pipi needs to go to a different box."
```
Comment (ajtadeo) [inline src/pages/Exercise1.tsx]: Pipi starts at address 2, so 11-2 should be 9 addresses. The correctAnswer is wrong here

File: src/pages/Exercise1.tsx [hunk 2]
```diff
@@ -82,16 +100,33 @@ const Exercise1: FC = () => {
...
+                    setCorrectAnswer={setCorrectAnswer}
+                    index={2}
                   />
                 </span>
               </p>
             </Question>
             <Question
-              correct="Correct! Now Pipi needs to..."
-              incorrect="Not quite. Think about ... Please try again."
+              correct="Correct! Pipi needs to move from address 11 to address 22. Thanks to you, Pipi found all of the boxes correctly!"
```
Comment (ajtadeo) [inline src/pages/Exercise1.tsx:107]: Pipi starts at address 11, so 22-11 = 11 addresses. The correctAnswer is wrong here

**Review by ajtadeo — CHANGES_REQUESTED** [review]

**Review by ajtadeo — APPROVED** [review]
