### PR TITLE
Use grid display to fix display in small screen of the exercise 1

### LINKED ISSUE #373: Minor Update: Fix Excercise 1 Buttons for Mobile
image
Fix the "check" buttons on this page so that they are on the background correctly for smaller screens

### PR DESCRIPTION
**Pull request by ChenghengLi**
## Summary

Closes #373 

I utilized a grid display to arrange all divs in a stacked format for screens smaller than 850px. Additionally, I adjusted the padding to optimize the layout for smaller screens.

## Screenshots

Some screenshots of the final results on small screen such as in a iphone SE.

No check buttons pressed
image
Incorrect answer
image
Correct answer
image
All correct answer
image

Some screeshots on bigger displays
Iphone 14 pro max
image
image
image

Laptop or tablet displays reamains as before
image

### CODE REVIEW

File: src/pages/Exercise1.tsx [hunk 1]
```diff
@@ -42,18 +42,21 @@ const Exercise1: FC = () => {
...
+                        { id: 2, name: '11', displayName: '11' },
+                        { id: 3, name: '12', displayName: '12' },
+                        { id: 4, name: '13', displayName: '13' },
+                      ]}
+                      correctAnswer={correctAnswer}
+                      index={0}
+                    />
+                  </span>
+                </span>{' '}
+                .
```
Comment (Dankco) [inline src/pages/Exercise1.tsx:59]: good catch! I didn't realize there was no period here.

**Review by Dankco — APPROVED** [review]
Nice work here! It looks so much better on smaller screens now. CSS can do pretty cool things sometimes.
